/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mainSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Screen Descriptions',
      items: [
        'Screen Descriptions/Overview',
        'Screen Descriptions/Main Menu',
        'Screen Descriptions/Mini Player',
        'Screen Descriptions/Home',
        'Screen Descriptions/Song Info',
        'Screen Descriptions/Party Mix',
        'Screen Descriptions/Player',
        'Screen Descriptions/Song Queue',
        'Screen Descriptions/Passenger',
        'Screen Descriptions/Search',
        'Screen Descriptions/Browse',
        'Screen Descriptions/Info',
        'Screen Descriptions/My Karaoke',
      ],
    },
    'UI Structure',
    {
      type: 'category',
      label: 'Passenger App',
      items: [
        'Passenger App/Overview',
        {
          type: 'category',
          label: 'Passenger Screens',
          items: [
            'Passenger App/Passenger Screens/Splash Screen',
            'Passenger App/Passenger Screens/Connection',
            'Passenger App/Passenger Screens/Player',
            'Passenger App/Passenger Screens/Song Queue',
            'Passenger App/Passenger Screens/Add Songs',
            'Passenger App/Passenger Screens/Browse',
            'Passenger App/Passenger Screens/Song Info',
            'Passenger App/Passenger Screens/Landscape',
          ],
        },
      ],
    },
    'Appendix A - Safety Features',
    'Appendix B - The Song Queue',
    'Appendix C - Queue Flowcharts',
  ],
   
};

export default sidebars;
