/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mainSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Screen descriptions',
      items: [
        'Screen descriptions/Overview',
        'Screen descriptions/Main Menu',
        'Screen descriptions/Mini Player',
        'Screen descriptions/Home',
        'Screen descriptions/Song Info',
        'Screen descriptions/Party Mix',
        'Screen descriptions/Player',
        'Screen descriptions/Song Queue',
        'Screen descriptions/Passenger',
        'Screen descriptions/Search',
        'Screen descriptions/Browse',
        'Screen descriptions/Info',
        'Screen descriptions/My Karaoke',
      ],
    },
    'UI structure',
    {
      type: 'category',
      label: 'Passenger App',
      items: [
        'Passenger App/Overview',
        {
          type: 'category',
          label: 'Passenger Screens',
          items: [
            'Passenger App/Passenger Screens/Splash Screen',
            'Passenger App/Passenger Screens/Connection',
            'Passenger App/Passenger Screens/Player',
            'Passenger App/Passenger Screens/Song Queue',
            'Passenger App/Passenger Screens/Add Songs',
            'Passenger App/Passenger Screens/Browse',
            'Passenger App/Passenger Screens/Song Info',
            'Passenger App/Passenger Screens/Landscape',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Scoring',
      items: [
        'Scoring/Overview',
        'Scoring/Scorable Songs',
        'Scoring/Scoring a song',
        'Scoring/Score Player',
        'Scoring/Score calculation',
        'Scoring/Final Score Display',
        'Scoring/Reactions',
        'Scoring/Scoring and the Song Queue',
        'Scoring/Scorable Song Info',
        'Scoring/Top Scores row',
      ],
    },
    'Appendix A - Safety Features',
    'Appendix B - The Song Queue',
    'Appendix C - Queue Flowcharts',
  ],
};

export default sidebars;
